### PR TITLE
DO NOT MERGE Enable incremental mode by default

### PR DESCRIPTION
**Pull request by slandelle**
I'm trying to enable incremental compiler by default.

The IT tests that test that `Mixed` compile order against Java/Scala circular references all fail.
Note that those tests pass when using non incremental (`all`) mode that launch a scalac process.

@jvican I'm a bit at a loss here. Could you please help?

### CODE REVIEW

**Comment by jvican** [comment]
I can help out with any questions you have, though I won't be able to look into it myself in at least the next two weeks. Could you copy/paste errors and clarify what's failing, what's not, and what is the expected behaviour? I'd need a little bit more of context before I can chime in

**Comment by slandelle** [comment]
@jvican Thanks a lot for chiming in! 

My Zinc code looks like [this](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/sbt_inc/SbtIncrementalCompiler.java). In particular, I'm correctly setting the compiler order [here](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L111).

Still, tests that verify `Mixed` compile order all fail, eg [this one](https://github.com/davidB/scala-maven-plugin/tree/master/src/it/testJavaAndScala):

```
[INFO] [INFO] Compiling 1 Scala source and 2 Java sources to /.../scala-maven-plugin/scala-maven-plugin/target/it/testJavaAndScala/target/classes ...
[INFO] [ERROR] [Error] /.../scala-maven-plugin/scala-maven-plugin/target/it/testJavaAndScala/src/main/java/JavaClass.java:1: cannot find symbol
[INFO]   symbol: class ScalaClass
[INFO] [ERROR] [Error] /.../scala-maven-plugin/scala-maven-plugin/target/it/testJavaAndScala/src/main/java/JavaClass.java:4: cannot find symbol
[INFO]   symbol:   method abstractJavaMethod()
[INFO]   location: variable test of type JavaClass
```

Am I missing something?

**Comment by jvican** [comment]
From that error, either of these two must be happening:

1. The compiler order is not being correctly set (maybe overridden somewhere?), which means that javac will compile the sources before scalac does, and then the referred Scala symbols from java sources will fail
2. The compiler order is correctly set and mixed compilation happens, but the javac compilation does not see the class files generated by scalac. Could be happening because the configured compile classpath does not contain the classes directory of the project (where scalac outputs compilation products)
  
A reminder: mixed compilation is a feature of the compiler where you allow Scala and java sources to refer to symbols in a circular fashion. The Scala compiler can break the circularity because it's capable of reading java source files and populating the Scala symbol table. So, first, scalac receives both Scala and Java source files (only generating class files for Scala symbols) and then javac is invoked with the class files generated by scalac.

**Comment by slandelle** [comment]
That's most likely 2! I remember adding output dir to classpath in Gatling impl but didn't check how classpath was implemented here. Will check. Thanks!

**Comment by slandelle** [comment]
Adding classes directory to the classpath did the trick for Mixed compile order.

Sadly, it broke some other tests, in particular this [one](https://github.com/davidB/scala-maven-plugin/tree/master/src/it/test_directory_with_class_name).

Here, the sources look like this:
sources

Compiles crashes with the following errors:

```
[ERROR] [Error] /Users/slandelle/Documents/dev/projects/scala-maven-plugin/scala-maven-plugin/target/it/test_directory_with_class_name/src/main/java/example/Foo2.java:3: Foo2 is already defined as package Foo2
[ERROR] [Error] /Users/slandelle/Documents/dev/projects/scala-maven-plugin/scala-maven-plugin/target/it/test_directory_with_class_name/src/main/scala/example/Foo.scala:3: Foo is already defined as package Foo
```

It seems the compiler misinterpret a folder containing resources for a package.

This test works just fine when compiling directly with `scala.tools.nsc.Main`, or when using Zinc without adding class directory to the classpath.

**Comment by jvican** [comment]
Mind that the classes directory at the beginning of the class path is absolutely mandatory for incremental compilation to work at all. The fact that mixed compilation was broken before also meant that incremental compilation wasn't working.
  
Re the last error: make sure the classes directories always have preference over the resource directories to avoid problems such as that one.

**Comment by slandelle** [comment]
> Re the last error: make sure the classes directories always have preference over the resource directories to avoid problems such as that one.

How can I do that?

The `maven-resources-plugin` copies resources into `/target/classes` during compile phase and has precedence over non maven core plugins so if we add the classes directory in the classpath, those resources will already be there when `scala-maven-plugin` kicks in.
The only solution I see is to move content elsewhere, compile and move things back, which is... err...

**Comment by jvican** [comment]
I don't know the specifics. What the test case is testing is a little bit awkward and I don't even understand how the previous zinc was working. So I'd figure out why it was working before. Another solution is to disable that test case completely...
  
If you have some other technical questions about incremental compilation, feel free to ping me!

**Comment by slandelle** [comment]
@jvican Thanks a lot for your help.
I agree this test is pretty awkward. @davidB where does it come from? I agree with @jvican that we shouldn't bother with this.

**Comment by davidB** [comment]
I don't remember from where this test come (it was in 2013), but from what I saw it passed with `recompilationMode all`, not with `incremental`. Because `incremental` becomes default, it meens that project/test that didn't specify `recompilationMode`, should explicitly become  `all`.

**Comment by slandelle** [comment]
> it means that project/test that didn't specify `recompilationMode`, should explicitly become `all`.

Will do, even though it's a bit sad to have it pass with one mode and not another.

**Comment by davidB** [comment]
> > it means that project/test that didn't specify `recompilationMode`, should explicitly become `all`.
> 
> Will do, even though it's a bit sad to have it pass with one mode and not another.

agree, but better than diseable or remove and document limitation of a mode.

**Comment by slandelle** [comment]
Tests should be fine now. @davidB Please let me know if I can cherry-pick on master.

**Comment by davidB** [comment]
Yes you can cherry-pick on master or rebase+merge

**Pull request closed without merging**
