### PR TITLE
hornor release and target options for non-incremental compile

### LINKED ISSUE #584: maven.compiler.target does not take effect when recompileMode is all
when recompileMode==all, the `release` and  `target` is not injected into the new process.

### PR DESCRIPTION
**Pull request by gzm55**
fix #584 and #585

### CODE REVIEW

**Comment by gzm55** [comment]
@davidB @slandelle could you plz review this pr?

**Review by davidB — APPROVED** [review]
LGTM

Thanks

**Comment by slandelle** [comment]
Sorry for the delay.
It would have been nice to add some tests, like I did for https://github.com/davidB/scala-maven-plugin/commit/36453a1b6b00e90c5e0877568a086c97f799ba12

**Comment by gzm55** [comment]
> Sorry for the delay. It would have been nice to add some tests, like I did for [36453a1](https://github.com/davidB/scala-maven-plugin/commit/36453a1b6b00e90c5e0877568a086c97f799ba12)

thanks, some ut for this pr are added in #588

**Pull request merged**
