### PR TITLE
support release compiler options for javac and scalac

### LINKED ISSUE #435: support maven.compiler.release property to control javac and scalac options
When compile with JDK 11, and generate objects targeting JVM 8, we should be able to config `javac -release ` and `scala-2.13 -release` options by `maven.compiler.release` property, like the [`maven-compiler-plugin`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release).

### PR DESCRIPTION
**Pull request by gzm55**
fix #435

### CODE REVIEW

**Comment by gzm55** [comment]
[ci checks](https://github.com/gzm55/scala-maven-plugin/runs/1795973122) on the fork commit are passed successfully, but those for pr are failed while cloning the codes.

**Comment by gzm55** [comment]
[ci checks](https://github.com/gzm55/scala-maven-plugin/runs/1795973122) on the fork commit are passed successfully, but those for pr are failed while cloning the codes.

**Comment by slandelle** [comment]
@gzm55 Please rebase your PR, it's currently conflicting.

**Comment by gzm55** [comment]
@slandelle conflict is resolved

**Comment by slandelle** [comment]
@gzm55 sorry, but I asked for a clean rebase, not an ugly merge commit (I know GitHub web ui can’t do that, you have to rebase locally and then push force in your fork).

**Comment by gzm55** [comment]
> @gzm55 sorry, but I asked for a clean rebase, not an ugly merge commit (I know GitHub web ui can’t do that, you have to rebase locally and then push force in your fork).

done

**Comment by slandelle** [comment]
Sorry for the late reply.
Could you please explain why you need to introduce 2 dedicated options? Why don't we also use `maven.compiler.release` for the Scala side?

**Comment by gzm55** [comment]
> Sorry for the late reply. Could you please explain why you need to introduce 2 dedicated options? Why don't we also use `maven.compiler.release` for the Scala side?

1. i see other options, e.g. args, are separated to `java-` and `scala-` stiles
2. may be some projects would like to have different target release for scala and java sources

**Comment by slandelle** [comment]
> may be some projects would like to have different target release for scala and java sources

Different bytecode versions in the same jar so some classes in there would fail to load? 
That sounds very unlikely to me.

I think we should aim for simplicity, ie not multiply the options.

**Comment by gzm55** [comment]
OK, i will merge the two options

**Comment by gzm55** [comment]
> OK, i will merge the two options

@slandelle now only one new option is added

**Review by slandelle — APPROVED** [review]

**Pull request merged**
