### PR TITLE
Zinc exclusions

### PR DESCRIPTION
**Pull request by slandelle**
In particular, exclude log4j 2 we don't use, so that it's not even in the classpath.

### CODE REVIEW

**Comment by slandelle** [comment]
@davidB PTAL. We should probably release to ease people, instead of having to explain that scala-maven-plugin is safe wrt Log4Shell.

**Comment by slandelle** [comment]
@davidB I tried to release by failed...

```
[INFO] [ERROR] Failed to execute goal com.github.github:site-maven-plugin:0.12:site (default) on project scala-maven-plugin: Server 'github' not found in settings -> [Help 1]
```

maven is BS'ing me here, I do have a server named  `github` in my settings.xml...

**Comment by davidB** [comment]
@slandelle I'll launch the release

**Comment by slandelle** [comment]
Thanks buddy!
Sorry, I can't investigate today why I can't publish, today's a day off for me.

**Comment by davidB** [comment]
no worries, Thanks all for your hard work.
The version 4.5.6 is released and should appear into maven central this afternoon.

**Comment by slandelle** [comment]
Thanks a lot!

**Pull request merged**
