### PR TITLE
First take at upgrading Zinc

### PR DESCRIPTION
**Pull request by slandelle**
There's most likely lots of cleaning up, but you can have a look.

### CODE REVIEW

**Comment by slandelle** [comment]
@davidB What's the point of `recompileMode`? `all` could be taken care of with `mvn clean`.  And `modified-only` vs `incremental` should be the same (taken care of by Zinc's analysis cache, right?).

**Comment by davidB** [comment]
@slandelle Great job,

About `recompileMode`, IMO
* `modify-only` could be dropped, it was a quick and dirty way to do incremental compile on plugin side (before zinc, sbt analysis,...), and the change to 4.x.x allow breaking change
* `all` should be keep, it's a way to say "I would not like to use incremental"
  * `clean` imply to drop every thing not only generated main or test classes (some project generate (re)sources,  do possibly heavy stuff that could be keep)
  * in continious compilation mode, I would like to recompile "all" with scalac

**Comment by slandelle** [comment]
@davidB Any idea why Travis fails? Same command works fine on my side.

So `all` would just bypass/ignore/not generate AnalysisStore, right?

**Comment by slandelle** [comment]
BTW, I upgraded to JDK8 to keep things simple (zinc dependency). IMHO, that's anyway the right thing to do in 2019 in a new major version.
Fine with you?

**Comment by davidB** [comment]
`all` ignore analysis and pass every sources file (in alphabetical order) to scalac.
(the sort is mandatory due to an old bug in scalac)

**Comment by davidB** [comment]
Yes for 4.x.x, I'm fine to drop support for < jdk1.8
Maybe I'll also remove some test for old version of scala.

I'll take a look to the travis error.

**Comment by slandelle** [comment]
Are you fine with making incremental the default ?

**Comment by davidB** [comment]
yes incremental could be the default

**Comment by davidB** [comment]
I found how to reproduce the travis issue locally:
```
./mvnw invoker:run -Dinvoker.test=test_goal_doc
```

I'll search for a fix, until that you can disable the test (add it to the list of test to exclude in pom.xml). I guess you can also remove the dependencies to bcel you add into top pom.xml

**Comment by davidB** [comment]
To simplify collaboration (and to thanks you), I'll add you as collaborator on the project, and merge the PR to master. So we can work on the 4.x.x.

**Comment by slandelle** [comment]
> I guess you can also remove the dependencies to bcel you add into top pom.xml

I forced bcel upgrade because maven site was crashing when parsing scala libraries' bytecode.

> I'll search for a fix, until that you can disable the test

Under way, thanks

> I'll add you as collaborator on the project, and merge the PR to master

Thanks!

**Comment by davidB** [comment]
Build passed:
- I removed the forced bcel upgrade on root pom.xml (bcel seems to be a dependency of the maven-project-info-reports-plugin not of maven-site-plugin)
- upgrade the test_goal_doc to use new version of the plugins  (maven-project-info-reports-plugin and maven-site-plugin) => bcel version up from 5.2 to 6.2

**Pull request merged**
